version: '3'
services:
  db:
    ports:
      - "3306:3306"
    image: "mariadb:10.3.5"
    command: mysqld --user=root --verbose
    restart: always
    environment:
      MYSQL_DATABASE: "myflaskapp"
      MYSQL_USER: "test"
      MYSQL_PASSWOR: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./dbcreation.sql:/tmp/dbcreation.sql
      - ./import.sh:/tmp/import.sh
  web:
    build: ./docker/web
    ports:
      - "5000:5000"
    restart: always
    links:
      - db
    depends_on:
      - db
