version: '3'
services:
  web:
    build: ./docker/web
    ports:
      - "5000:5000"
    restart: always
    links:
      - db
    depends_on:
      - db
  db:
    build: ./docker/db
    ports:
      - "3306:3306"
    image: "mysql:8.0.4"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
