version: '3'
services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db
  db:
    image: "mysql:8.0.4"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
