version: '3'
services:
  db:
    image: "armv7/armhf-mysql:5.5"
    ports:
      - "3306:3306"
    command: mysqld -uroot --verbose
    restart: always
    environment:
      MYSQL_DATABASE: "myflaskapp"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  web:
    build: ./docker/web
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
